### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by markus-zhang-unity** [spectacles-ci/spectacles#610]
Hi experts,

I encountered this message during a run of spectacles. There was an earlier issue that was similar but in a different place. Here is the traceback:

```
Traceback (most recent call last):
  File "/Users/markus.zhang/PycharmProjects/spectest/venv/lib/python3.8/site-packages/spectacles/cli.py", line 153, in wrapper
    return function(*args, **kwargs)
  File "/Users/markus.zhang/PycharmProjects/spectest/venv/lib/python3.8/site-packages/spectacles/cli.py", line 307, in main
    run_content(
  File "/Users/markus.zhang/PycharmProjects/spectest/venv/lib/python3.8/site-packages/spectacles/utils.py", line 61, in timed_function
    result = fn(*args, **kwargs)
  File "/Users/markus.zhang/PycharmProjects/spectest/venv/lib/python3.8/site-packages/spectacles/cli.py", line 783, in run_content
    results = runner.validate_content(
  File "/Users/markus.zhang/PycharmProjects/spectest/venv/lib/python3.8/site-packages/spectacles/runner.py", line 467, in validate_content
    validator.validate(project)
  File "/Users/markus.zhang/PycharmProjects/spectest/venv/lib/python3.8/site-packages/spectacles/validators/content.py", line 70, in validate
    errors = self._get_errors_from_result(project, content, content_type)
  File "/Users/markus.zhang/PycharmProjects/spectest/venv/lib/python3.8/site-packages/spectacles/validators/content.py", line 148, in _get_errors_from_result
    space=result[content_type]["space"]["name"],

```

So I looked at the code, added one line to print the `content` and figured out that this item is probably causing the issue:

```
{'look': None, 'dashboard': {'description': None, 'title': 'Data Monitoring v2.0', 'space': None, 'folder': None, 'id': 1654}, 'dashboard_element': {'body_text': None, 'dashboard_id': 1654, 'id': 17788, 'look_id': None, 'note_display': None, 'note_state': None, 'note_text': None, 'note_text_as_html': None, 'query_id': 1097027, 'subtitle_text': None, 'title': 'CENSORED INTERNAL', 'title_hidden': False, 'title_text': None, 'type': 'vis', 'rich_content_json': None}, 'dashboard_filter': None, 'scheduled_plan': None, 'alert': {'id': 317, 'lookml_dashboard_id': '1654', 'lookml_link_id': None, 'custom_title': 'censored internal title'}, 'lookml_dashboard': None, 'lookml_dashboard_element': None, 'errors': [{'message': 'Unknown explore "gg_ua_game_summary_daily".', 'field_name': None, 'model_name': 'my_model', 'explore_name': 'my_explore', 'removable': None}], 'id': 820}

```
The `space` is None so it's causing line 148 to throw an error because ["space"] gives a None so it doesn't have a ["name"] element. 

I managed to patch it up by modifying line 148 to:

```
space=result[content_type]["space"]["name"] if result[content_type]["space"] is not None else None,
```

However I don't know how to deploy the patched version in GitHub Action so maybe you can look into it and patch properly? I'm a bad Python programmer so I'm sure there are better ways.

Thanks!

**Comment by DylanBaker** [comment]
Hey @markus-zhang-unity. It looks like you might be running an old version of Spectacles. Could you please run `spectacles --version` to confirm which version you're using?

You should be able to upgrade the version by running `pip install --upgrade spectacles`. I would try doing that and then re-running the command you had the issue with.

**Comment by markus-zhang-unity** [comment]
Hi @DylanBaker I'm using 2.2.0 and looks like the most current version. Thanks~~

**Comment by DylanBaker** [comment]
Ah. Apologies. I was looking at the code for our upcoming release candidate and not that release. 

I think there's an upcoming release that this might have been solved in. Could you please try the release candidate for 2.3.0 by running `pip install spectacles==2.3.0rc2` and run it again?

**Comment by markus-zhang-unity** [comment]
Hi @DylanBaker thanks! I just ran it again and this time is better but it still throws the same error. Basically it does manage to run through most of the tests (unlike last time it stopped without showing any of the pass/fail message) but still throws the error message:

```
Traceback (most recent call last):
  File "/Users/markus.zhang/PycharmProjects/spectest/venv/lib/python3.8/site-packages/spectacles/cli.py", line 155, in wrapper
    return function(*args, **kwargs)
  File "/Users/markus.zhang/PycharmProjects/spectest/venv/lib/python3.8/site-packages/spectacles/cli.py", line 315, in main
    asyncio.run(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/markus.zhang/PycharmProjects/spectest/venv/lib/python3.8/site-packages/spectacles/utils.py", line 60, in timed_function
    result = await fn(*args, **kwargs)
  File "/Users/markus.zhang/PycharmProjects/spectest/venv/lib/python3.8/site-packages/spectacles/cli.py", line 845, in run_content
    error["metadata"]["space"],
KeyError: 'space'
```

**Comment by joshtemple** [comment]
Thanks for all the help @markus-zhang-unity! This is a bug related to moving from Looker API version 3.1 (now deprecated) to 4.0 (#575). I'll have a fix pushed out later today.

**Comment by markus-zhang-unity** [comment]
Thanks a lot @joshtemple just curious when can we have a stable version with this implemented? Or should I go with dev build first?

**Comment by joshtemple** [comment]
Should be able to have a new release candidate out today!

**Comment by joshtemple** [comment]
@markus-zhang-unity this fix was released in the latest release candidate. You can install with `pip install spectacles==2.3.0rc3`. Let us know if this fixes things for you!

**Comment by markus-zhang-unity** [comment]
Thanks @joshtemple will give it a try!
