### ISSUE TITLE
Issues with new Looker users checking out branches

### ISSUE THREAD

**Issue by friendofasquid** [spectacles-ci/spectacles#729]
Not specific to Spectacles, but something we uncovered while using it. We would frequently, but intermittently, get Git related errors in Looker when running Spectacles in our CI pipeline. It was either "Unable to check out branch" or "Unable to reset to remote".

What I've discovered is that for newly created Looker users, there's a delay of 2-3 minutes before that user is able to checkout code. So during our CI checks, I've added the following. Note this code runs as newly created user, and fails 2-5 times on the `update_git_branch` call until ultimately succeeding. I have a ticket open with Google on this.

```python
while True:
    try:
        print("Switching to dev mode.")
        response = sdk.update_session(models.WriteApiSession(workspace_id="dev"))

        print(f"Updating branch to `{os.environ['LOOKER_GIT_BRANCH']}`.")
        response = sdk.update_git_branch(
            project_id=os.environ["LOOKER_PROJECT"]
            body=models.WriteGitBranch(
                name=os.environ["LOOKER_GIT_BRANCH"],
            )
        )

        print("Resetting branch to remote.")
        sdk.reset_project_to_remote(
            project_id=os.environ["LOOKER_PROJECT"]
        )
    except looker_sdk.error.SDKError as e:
        print("Failure. Trying again.")
        continue
    break
```

Almost certainly the `reset_to_remote` is not needed, since we're checking out the branch, but keeping it in there just to be sure everything works as expected.

**Comment by attrivivekFF** [comment]
Thanks @friendofasquid for sharing this code. We have been facing the same issue on our spectacles CI tests for quite some time while checking out git branch. Can you please help us know where to add this piece of code?

**Comment by friendofasquid** [comment]
We run that code just before we run Spectacles. Easy as that. If you end up with errors using that code, it gives you something more concrete to raise with Looker support as well.

**Comment by joshtemple** [comment]
Hey @friendofasquid, thank you for sharing this! Please keep us updated on your ticket with Google. It sounds like they are probably setting up the local Git repo for the new user on their side in the background.

**Comment by friendofasquid** [comment]
Support has suggested running `update_user` with `models_dir_validated=True` as a workaround. This had no effect for me, but YMMV.

**Comment by friendofasquid** [comment]
We've noticed that even switching the new user to Dev mode in the Looker UI errors if the user is newly created via the API. So I suspect there are a few async processes happening in the background and the API doesn't block until they're finished.

**Comment by friendofasquid** [comment]
From support:

> […] This appears to be a bug in looker, possibly caused by a race condition between cloning a remote git repository with an HTTPS transport, and using the results of that operation.Our team is working to solve this potential problem in Looker.
>
> In the meantime, you may be able to make progress by changing the parameters of the Git remote configuration to use a 'git://' protocol instead of a 'https://' reference.

**Comment by friendofasquid** [comment]
Just received word that this is fixed in version 23.16.47+. If you encounter this bug, you might need to raise a support ticket and request the patch.

I cannot confirm if it does indeed fix the issue yet.

**Comment by friendofasquid** [comment]
This patch has fixed the issue for me.

**Comment by attrivivekFF** [comment]
@friendofasquid Thanks for posting this. We got our version upgraded but still facing this error. I chatted with looker support, they need this ticket or case id. Can you please share the ticket ID or case Id you raised with looker support?

**Comment by friendofasquid** [comment]
Case #585320. 

@attrivivekFF — can you share a bit more about your setup? Have you tried skipping Spectacles and using the Looker API to see if that works? I'm wildly speculating, but could it be that the user doesn't have Github credentials as user attributes in Looker?
